tabItem(tabName = "scsel",
        tags$hr(),
        h4("Welcome to SciView!"),
        tags$hr(),
        shiny::HTML("SciViewer is an interactive visualization platform for single cell datasets. 
                             This section allows you to browse the study for a list of available studies. 
                             The second section of the platform allows exploration of a selected single cell dataset using multiple interactive plots.
                             These plots and data visualizations are highly customizable -depending on the project needs. 
                             The visualizations are gene-centric.
                             In the last section, you can compare the expression of a selected gene across multiple datasets. The gene expression comparison
                             across studies is qualitative, but can give an understanding of the expression patterns of the gene across two selected studies. 
                             The platform further allows visualization of CITE-seq data. 
                             <br>"),
        tags$br(),
        tags$hr(),
        h4("Select scRNA-seq study"),
        tags$hr(),
        fluidRow(
                column(width = 8,
                       shiny::HTML("You can filter the available studies for species, disease, tissue, user-defined cell type or sample size. 
                             The selected study from the list is available for further data exploration. The details of the selected study 
                              are displayed at the end of the page.")
                       #selectInput("sc_study",label="",choices = NULL,multiple = F),
                ),
                column(width = 2,
                       actionButton("browse_study", "Browse more studies", style="text-align:left; font-size:100%"),
                       bsTooltip("browse_study", "Allows browsing additional studies from local drive for interactive visualization",
                                 "left", options = list(container = "body")),
                       bsModal("browse_mode", strong("Browse single cell study", style="color:#6a51a3; font-size:110%"), 
                               "browse_study", size = "large",
                               shiny::HTML("The <b>Add more studies!</b> button allows you to chose the folder locations from the hard-drive (/home; .; C:/  ).
                             Please select appropriate folder that contains database files (.db) for single cell experiments. Please note that the 
                             database files are generated by <i><u>SciViewerIn</u></i> application by using the single cell data in either Seurat or .h5ad format.  
                              
                             If the directory of choice is not availalbe, please input the directory path in the box below and then explore the folder 
                             using <b>Add more studies!</b> button.<br> "),
                               tags$br(),
                               fluidRow(column(width=6,textInput("datadir", "browse directory path", NULL)),
                                        column(width=4,tags$br(),actionButton("ab573dfg3","Go!",icon = icon("arrows-rotate"))),
                                        column(width=2)
                               ),
                               verbatimTextOutput('direxists'),
                               tags$br(),
                               shinyFilesButton(id = 'infile', label = '+ Add more studies!',title =  'Please select a dataset', multiple = T),
                               tags$br()
                       )
                ),
                column(width = 2,
                       actionButton("conf_study", "Configure study list", style="text-align:left; font-size:100%"),
                       bsTooltip("conf_study", "Want to skip browsing individual studies? Configure the database paths in the app.",
                                 "left", options = list(container = "body")),
                       bsModal("conf_mode", strong("configure paths of various single cell studies", style="color:#6a51a3; font-size:110%"), 
                               "conf_study", size = "large",
                               shiny::HTML("<b>Manage list of database files. </b> 
                                           For advanced users, please add full paths of the database (.db) files in the section below.
                                           This option will avoid selecting individual single cell study for visualization. The database paths
                                           are stored in the application and will be used next time while running it. The provided studies will
                                           be listed in the table where the users can select individual studies for interactive visualization and comparisons.<br>
                                           <br>"),
                               verbatimTextOutput('availstudypaths'),
                               tags$br(),
                               fluidRow(column(width=3,actionButton("ab573wer","Add studies",icon = icon("cog"))),
                                        column(width=3,actionButton("ab573rty","Replace list",icon = icon("cog"))),
                                        column(width=6)
                               ),
                               shiny::HTML("<br><u>Provide <b>comma(,)</b> separated file paths</u><br>"),
                               tags$br(),
                               conditionalPanel(
                                       condition = "input.ab573wer>'0'",
                                       textInput("ab573wer_db", "Add more studies to existing list", NULL,width = "400px"),
                                       actionButton("ab573wer_dbgo","Save",icon = icon("cog"))
                               ),
                               conditionalPanel(
                                       condition = "input.ab573rty>'0'",
                                       textInput("ab573rty_db", "Replace studies from the list", NULL,width = "400px"),
                                       actionButton("ab573rty_dbgo","Save",icon = icon("cog"))
                               ),
                               tags$br()
                       )
                )
                       
        ),
        tags$br(),
        #-- table 
        #reactable::reactableOutput("browse_studytable")%>% shinycssloaders::withSpinner(color="#0dc5c1"),
        DT::dataTableOutput("browse_studytable") %>% shinycssloaders::withSpinner(color="#0dc5c1"),
        tags$br(),
        ##---
        fluidRow(
                column(width = 12,
                       box(
                               #shiny::HTML("<b> Details of the selected study:</b><br>"), 
                               htmlOutput("sc_study_attribs"),
                               solidHeader = T, collapsible = F,collapsed = F, width = 12
                       )
               )
        ),
        tags$br()
)## End of scsel
